In [3]:
import numpy as np 

In [4]:
x = [
    [2, -2, 6],
    [-2, 4, 3],
    [-1, 8, 4],
]

y = [
    16,
    0,
    -1
]

In [8]:

def diagonal_dominance(matrix):
    matrix = np.array(matrix) 
    mat_diag = np.diag(np.abs(matrix))
    np.fill_diagonal(matrix, 0)
    off_diag = np.sum(np.abs(matrix), axis=1)
        
    print(matrix)
    print(mat_diag)
    print(off_diag)    
    return np.all(mat_diag > off_diag)

diagonal_dominance(x)

[[ 0 -2  6]
 [-2  0  3]
 [-1  8  0]]
[2 4 4]
[8 5 9]


False

In [7]:
def gauss_seidel(x,y):
   if not diagonal_dominance(x):
       print("Not Diagonal Dominant")
       return
   
   x = np.array(x)
   y = np.array(y)
   x_diag = np.array(np.diag(x))
   np.fill_diagonal(x, 0)
   
   max_iter = 50
   threshold = 0.005
   x = -x
   
   res_old = np.zeros(x_diag.shape)
   for iter in range(max_iter):
        res_new = np.array(res_old)  
        for idx, row in enumerate(x):
           res_new[idx] = (y[idx] + np.dot(res_new, row)) / x_diag[idx]
        
        diff = np.sqrt(np.dot(res_new - res_old, res_new - res_old))
        print(f"Iteration #{iter + 1} : {res_new}")
        print(f"diff = {diff}")
        
        if(diff <= threshold):
            print("Convergence")
            return
        
        res_old = res_new
        
gauss_seidel(x,y)
    

[[ 0 -2  6]
 [-2  0  3]
 [-1  8  0]]
[2 4 4]
[8 5 9]
Not Diagonal Dominant
